USE [ACKAppDB]
GO

/****** Object:  Table [dbo].[KULLANICIBILGI]    Script Date: 08/10/2014 20:52:48 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[KULLANICIBILGI](
	[KULLANICIADI] [varchar](50) NULL,
	[SIFRE] [varchar](50) NULL,
	[YETKI] [varchar](50) NULL
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

-------------------------------------------------------------------

USE [ACKAppDB]
GO

/****** Object:  Table [dbo].[PERSONELBILGI]    Script Date: 08/10/2014 20:53:15 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[PERSONELBILGI](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[AD] [char](50) NOT NULL,
	[SOYAD] [char](100) NOT NULL,
 CONSTRAINT [PK_PERSONELBILGI] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO
