USE [ACKAppDB]
GO

/****** Object:  Table [dbo].[KULLANICIBILGI]    Script Date: 08/10/2014 20:52:48 ******/

CREATE TABLE [dbo].[KULLANICIBILGI](
	[KULLANICIADI] [varchar](50) NULL,
	[SIFRE] [varchar](50) NULL,
	[YETKI] [varchar](50) NULL
) ON [PRIMARY]

/****** Object:  Table [dbo].[PERSONELBILGI]    Script Date: 08/10/2014 20:53:15 ******/

CREATE TABLE [dbo].[PERSONELBILGI](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[AD] [char](50) NOT NULL,
	[SOYAD] [char](100) NOT NULL,
 CONSTRAINT [PK_PERSONELBILGI] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]


/****** Object:  Table [dbo].[REF_TESLIMSEKLI]    Script Date: 08/12/2014 22:59:38 ******/

CREATE TABLE [dbo].[REF_TESLIMSEKLI](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[AD] [varchar](50) NOT NULL,
	[NOVA] [varchar](50) NOT NULL,
	[KROMA] [varchar](50) NOT NULL,
	[GUARD] [varchar](50) NOT NULL,
 CONSTRAINT [PK_REF_TESLIMSEKLI] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]


/****** Object:  Table [dbo].[REF_MONTAJSEKLI]    Script Date: 08/12/2014 22:59:35 ******/

CREATE TABLE [dbo].[REF_MONTAJSEKLI](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[AD] [varchar](50) NOT NULL,
	[NOVA] [varchar](50) NOT NULL,
	[KROMA] [varchar](50) NOT NULL,
	[GUARD] [varchar](50) NOT NULL,
 CONSTRAINT [PK_REF_MONTAJSEKLI] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]


/****** Object:  Table [dbo].[REF_KILITSISTEM]    Script Date: 08/12/2014 22:59:31 ******/

CREATE TABLE [dbo].[REF_KILITSISTEM](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[AD] [varchar](50) NOT NULL,
	[NOVA] [varchar](50) NOT NULL,
	[KROMA] [varchar](50) NOT NULL,
	[GUARD] [varchar](50) NOT NULL,
 CONSTRAINT [PK_REF_KILITSISTEM] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]


/****** Object:  Table [dbo].[REF_KAPISERI]    Script Date: 08/12/2014 22:59:28 ******/

CREATE TABLE [dbo].[REF_KAPISERI](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[AD] [varchar](50) NOT NULL,
 CONSTRAINT [PK_REF_KAPISERI] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]


/****** Object:  Table [dbo].[REF_KAPIRENK]    Script Date: 08/12/2014 22:59:24 ******/

CREATE TABLE [dbo].[REF_KAPIRENK](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[AD] [varchar](50) NOT NULL,
	[NOVA] [varchar](50) NOT NULL,
	[KROMA] [varchar](50) NOT NULL,
	[GUARD] [varchar](50) NOT NULL,
 CONSTRAINT [PK_REF_KAPIRENK] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]


/****** Object:  Table [dbo].[REF_KAPIMODEL]    Script Date: 08/12/2014 22:59:21 ******/

CREATE TABLE [dbo].[REF_KAPIMODEL](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[KAPISERIID] [int] NOT NULL,
	[AD] [varchar](50) NOT NULL,
 CONSTRAINT [PK_REF_KAPIMODEL] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]


/****** Object:  Table [dbo].[REF_ESIK]    Script Date: 08/12/2014 22:59:17 ******/

CREATE TABLE [dbo].[REF_ESIK](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[AD] [varchar](50) NOT NULL,
	[NOVA] [varchar](50) NOT NULL,
	[KROMA] [varchar](50) NOT NULL,
	[GUARD] [varchar](50) NOT NULL,
 CONSTRAINT [PK_REF_ESIK] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]


/****** Object:  Table [dbo].[REF_CITA]    Script Date: 08/12/2014 22:59:14 ******/

CREATE TABLE [dbo].[REF_CITA](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[AD] [varchar](50) NOT NULL,
	[NOVA] [varchar](50) NOT NULL,
	[KROMA] [varchar](50) NOT NULL,
	[GUARD] [varchar](50) NOT NULL,
 CONSTRAINT [PK_REF_CITA] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]


/****** Object:  Table [dbo].[REF_AKSESUARRENK]    Script Date: 08/12/2014 22:59:08 ******/

CREATE TABLE [dbo].[REF_AKSESUARRENK](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[AD] [varchar](50) NOT NULL,
	[NOVA] [varchar](50) NULL,
	[KROMA] [varchar](50) NULL,
	[GUARD] [varchar](50) NULL,
 CONSTRAINT [PK_REF_AKSESUARRENK] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
