USE [ACKAppDB]
GO

CREATE TABLE [dbo].[KULLANICIBILGI](
	[KULLANICIADI] [varchar](50) NOT NULL,
	[SIFRE] [varchar](50) NOT NULL,
	[YETKI] [varchar](50) NOT NULL,
 CONSTRAINT [PK_KULLANICIBILGI] PRIMARY KEY CLUSTERED 
(
	[KULLANICIADI] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]


------------------------------------------




CREATE TABLE [dbo].[PERSONELBILGI](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[AD] [char](50) NOT NULL,
	[SOYAD] [char](100) NOT NULL,
 CONSTRAINT [PK_PERSONELBILGI] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]



------------------------------------------



CREATE TABLE [dbo].[REF_AKSESUARRENK](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[AD] [varchar](50) NOT NULL,
	[NOVA] [bit] NOT NULL,
	[KROMA] [bit] NOT NULL,
	[GUARD] [bit] NOT NULL,
 CONSTRAINT [PK_REF_AKSESUARRENK] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]


------------------------------


CREATE TABLE [dbo].[REF_ALUMINYUMRENK](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[AD] [varchar](50) NOT NULL,
	[NOVA] [bit] NOT NULL,
	[KROMA] [bit] NOT NULL,
	[GUARD] [bit] NOT NULL,
 CONSTRAINT [PK_REF_ALUMINYUMRENK] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

-------------------------------------


CREATE TABLE [dbo].[REF_CITA](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[AD] [varchar](50) NOT NULL,
	[NOVA] [bit] NOT NULL,
	[KROMA] [bit] NOT NULL,
	[GUARD] [bit] NOT NULL,
 CONSTRAINT [PK_REF_CITA] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]


-------------------------------------------


CREATE TABLE [dbo].[REF_CONTARENK](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[AD] [varchar](50) NOT NULL,
	[NOVA] [bit] NOT NULL,
	[KROMA] [bit] NOT NULL,
	[GUARD] [bit] NOT NULL,
 CONSTRAINT [PK_REF_CONTARENK] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]


----------------------------------------------



CREATE TABLE [dbo].[REF_ESIK](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[AD] [varchar](50) NOT NULL,
	[NOVA] [bit] NOT NULL,
	[KROMA] [bit] NOT NULL,
	[GUARD] [bit] NOT NULL,
 CONSTRAINT [PK_REF_ESIK] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]


----------------------------------------------


CREATE TABLE [dbo].[REF_KAPIMODEL](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[KAPISERIID] [int] NOT NULL,
	[AD] [varchar](50) NOT NULL,
 CONSTRAINT [PK_REF_KAPIMODEL] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]


----------------------------------------------



CREATE TABLE [dbo].[REF_KAPIRENK](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[AD] [varchar](50) NOT NULL,
	[NOVA] [bit] NOT NULL,
	[KROMA] [bit] NOT NULL,
	[GUARD] [bit] NOT NULL,
 CONSTRAINT [PK_REF_KAPIRENK] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]


----------------------------------------------

CREATE TABLE [dbo].[REF_KAPISERI](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[AD] [varchar](50) NOT NULL,
 CONSTRAINT [PK_REF_KAPISERI] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]


----------------------------------------------


CREATE TABLE [dbo].[REF_KILITSISTEM](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[AD] [varchar](50) NOT NULL,
	[NOVA] [bit] NOT NULL,
	[KROMA] [bit] NOT NULL,
	[GUARD] [bit] NOT NULL,
 CONSTRAINT [PK_REF_KILITSISTEM] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]


----------------------------------------------

CREATE TABLE [dbo].[REF_MONTAJSEKLI](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[AD] [varchar](50) NOT NULL,
	[NOVA] [bit] NOT NULL,
	[KROMA] [bit] NOT NULL,
	[GUARD] [bit] NOT NULL,
 CONSTRAINT [PK_REF_MONTAJSEKLI] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

----------------------------------------------


CREATE TABLE [dbo].[REF_PERVAZTIP](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[AD] [varchar](50) NOT NULL,
	[NOVA] [bit] NOT NULL,
	[KROMA] [bit] NOT NULL,
	[GUARD] [bit] NOT NULL,
 CONSTRAINT [PK_REF_PERVAZTIP] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]



----------------------------------------------

CREATE TABLE [dbo].[REF_TABLOLAR](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[AD] [varchar](50) NOT NULL,
	[TABLO] [varchar](50) NOT NULL,
 CONSTRAINT [PK_REF_TABLOLAR] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

----------------------------------------------


CREATE TABLE [dbo].[REF_TACTIP](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[AD] [varchar](50) NOT NULL,
	[NOVA] [bit] NOT NULL,
	[KROMA] [bit] NOT NULL,
	[GUARD] [bit] NOT NULL,
 CONSTRAINT [PK_REF_TACTIP] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]


----------------------------------------------



CREATE TABLE [dbo].[REF_TESLIMSEKLI](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[AD] [varchar](50) NOT NULL,
	[NOVA] [bit]  NOT NULL,
	[KROMA] [bit]  NOT NULL,
	[GUARD] [bit] NOT NULL,
 CONSTRAINT [PK_REF_TESLIMSEKLI] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

/****** Object:  Table [dbo].[HATA]    Script Date: 14.8.2014 17:25:29 ******/

CREATE TABLE [dbo].[HATA](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[MODULEID] [int] NULL,
	[EVENTLOGENTRYTYPEID] [int] NULL,
	[EXCEPTION] [nvarchar](max) NULL,
	[PAGEURL] [nvarchar](500) NULL,
	[METHODNAME] [nvarchar](100) NULL,
	[MESSAGE] [nvarchar](500) NULL,
	[USERIDENTITY] [nvarchar](20) NULL,
	[PCNAME] [nvarchar](50) NULL,
	[USERAUTHORITY] [nvarchar](50) NULL,
	[EXTENDEDPROPERTIES] [nvarchar](50) NULL,	
	[USERNAME] [nvarchar](50) NULL,
 CONSTRAINT [PK_HATA] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
