USE [master]
GO
CREATE LOGIN [AckAppUser] WITH PASSWORD=N'1Qaz2wSx!', DEFAULT_DATABASE=[ACKAppDB], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
USE [ACKAppDB]
GO
CREATE USER [AckAppUser] FOR LOGIN [AckAppUser]
GO
USE [ACKAppDB]
GO
EXEC sp_addrolemember N'db_owner', N'AckAppUser'
GO